### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by NoLooseEnds** [wolfv6/rclone_jobber#1]
Hi, thanks for this. :)

I'm just testing out rclone and this script helps to make it more of a backup tool rather than just a sync tool.

A couple of suggestions that popped up just now:

1. Add an option to write the warnings to the journalctl. At least I have this on a VM, and not on my desktop. So the notify pop-up part does not work.

This command should work:
> printf "$message" | systemd-cat -t RCLONE_JOBBER

2. Log rotation in the script? Not sure if that is a good idea, or just to set up a log rotation manually. At least the initial backup will be huge and fill up the log file.

I also set up this to use the conf and filter file from the same directory as the script. That makes the most sense to me. All in one place if I i.e are going to put it on another VM, etc.

To make it a bit easier for myself I made a symlink of the config file to the default rclone directory. An alternative method could be to set up an alias in .bashrc/.zshrc/etc.

```
rclone_jobber=<path-to-backup-script-directory> #path to rclone_jobber directory
remote=<name of remote> #added this

source="<path-to-source>"
dest="${remote}:"
move_old_files_to="dated_directory"
options="--config ${rclone_jobber}/rclone.conf --filter-from=${rclone_jobber}/filter_rules"
monitoring_URL=""

${rclone_jobber}/rclone_jobber.sh "$source" "$dest" "$move_old_files_to" "$options" "$(basename $0)" "$monitoring_URL"
```

Thanks!

**Comment by wolfv6** [comment]
NoLooseEnds,
Thanks for the suggestions, I have implemented the first two in rclone_jobber:

1. Add option to write warnings to the journalctl.
     printf "$message" | systemd-cat -t RCLONE_JOBBER
2. Add log rotation to tutorial.
3. conf in the same directory as the script.
   Not going to change this because it adds an extra step and indirection for people making simple backups from desktop.
   This would only effect job files, and people will write their own job files any ways.
4. Filter file in the same directory as the script.
   Not going to change this because all the files in examples/ directory are for the tutorial.
   e.g. the rclone_jobber/examples/job_backup_to_remote.sh uses rclone_jobber/examples/filter_rules
   This would only effect job files, and some people won't even use a filter rules file.

I added https://github.com/wolfv6/rclone_jobber/blob/master/rclone_jobber_tutorial.org#logging-options for items 1 and 2.
I added a rclone_jobber/examples/README.org file so that items 3 and 4 make more sense.

Changes are now in master branch (version 1.2).
